"""Generate an ActionPlan from an IncidentPacket."""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any

LLM_PROVIDER = os.environ.get("LLM_PROVIDER", "stub")
LLM_MODEL = os.environ.get("LLM_MODEL", "")


def _derive_priority(findings: list[dict]) -> str:
    max_conf = max((f.get("confidence", 0) for f in findings), default=0)
    if max_conf >= 0.9:
        return "P1"
    if max_conf > 0.8:
        return "P1"
    return "P2"


def _build_jira_description(packet: dict) -> str:
    lines = []
    lines.append(f"*Incident*: {packet.get('incident_id', 'N/A')}")
    lines.append(f"*Service*: {packet.get('service', 'N/A')}")
    lines.append(f"*Environment*: {packet.get('environment', 'N/A')}")
    tw = packet.get("time_window", {})
    if tw:
        lines.append(f"*Time Window*: {tw.get('start', '')} → {tw.get('end', '')}")
    lines.append("")

    findings = packet.get("findings", [])
    if findings:
        lines.append("h3. Findings")
        for f in findings[:10]:
            conf = f.get("confidence", 0)
            lines.append(f"- [{conf:.0%}] {f.get('summary', '')[:300]}")
        lines.append("")

    limits = packet.get("limits", [])
    if limits:
        lines.append("h3. Limits / gaps")
        for lim in limits[:5]:
            lines.append(f"- {lim[:200]}")
        lines.append("")

    actions = packet.get("next_actions", [])
    if actions:
        lines.append("h3. Suggested next actions")
        for a in actions[:5]:
            lines.append(f"- {a.get('summary', '')[:200]}")
            for cmd in a.get("commands", [])[:2]:
                lines.append(f"  {{code}}{cmd[:200]}{{code}}")
            for lnk in a.get("links", [])[:2]:
                lines.append(f"  [Link|{lnk}]")
        lines.append("")

    owners = packet.get("suspected_owners", [])
    if owners:
        lines.append("h3. Suspected owners")
        for o in owners[:3]:
            lines.append(f"- repo={o.get('repo', '?')} confidence={o.get('confidence', 0):.0%}")
        lines.append("")

    erefs = packet.get("all_evidence_refs", [])
    if erefs:
        lines.append("h3. Evidence references")
        for e in erefs[:10]:
            lines.append(f"- {e.get('collector_type', '?')}: s3://{e.get('s3_bucket', '')}/{e.get('s3_key', '')} (sha256={e.get('sha256', '')[:16]}…)")
        lines.append("")

    lines.append("----")
    lines.append("_Auto-generated by opsrunbook-copilot._")

    return "\n".join(lines)


def _build_teams_body(packet: dict, jira_ref: dict | None) -> str:
    lines = []
    iid = packet.get("incident_id", "N/A")
    svc = packet.get("service", "N/A")
    env = packet.get("environment", "N/A")
    lines.append(f"**Incident {iid}** — {svc} ({env})")
    lines.append("")

    findings = packet.get("findings", [])
    if findings:
        lines.append(f"**{len(findings)} finding(s)**")
        for f in findings[:3]:
            lines.append(f"- [{f.get('confidence', 0):.0%}] {f.get('summary', '')[:150]}")
        lines.append("")

    erefs = packet.get("all_evidence_refs", [])
    lines.append(f"Evidence objects: {len(erefs)}")

    if jira_ref:
        lines.append(f"\nJira: [{jira_ref.get('issue_key', '')}]({jira_ref.get('url', '')})")

    return "\n".join(lines)


def generate_action_plan(
    packet: dict,
    dry_run: bool = True,
) -> dict[str, Any]:
    incident_id = packet.get("incident_id", "")
    service = packet.get("service", "")
    environment = packet.get("environment", "dev")
    findings = packet.get("findings", [])
    erefs = packet.get("all_evidence_refs", [])
    owners = packet.get("suspected_owners", [])

    priority = _derive_priority(findings)
    jira_title = f"[{environment}] {service}: Incident {incident_id} – initial analysis"
    jira_desc = _build_jira_description(packet)

    collector_run_id = packet.get("collector_run_id", "")

    actions = [
        {
            "action_type": "create_jira_ticket",
            "priority": priority,
            "title": jira_title,
            "description_md": jira_desc,
            "evidence_refs": erefs[:10],
            "links": [],
            "dry_run": dry_run,
        },
        {
            "action_type": "notify_teams",
            "priority": priority,
            "title": f"Incident {incident_id} analyzed ({service}/{environment})",
            "description_md": "",
            "evidence_refs": erefs[:10],
            "links": [],
            "dry_run": dry_run,
        },
        {
            "action_type": "create_github_pr",
            "priority": priority,
            "title": f"Incident {incident_id} – {service}/{environment} initial analysis",
            "description_md": "",
            "evidence_refs": erefs[:10],
            "links": [],
            "dry_run": dry_run,
            "context": {
                "incident_id": incident_id,
                "collector_run_id": collector_run_id,
                "service": service,
                "environment": environment,
                "suspected_owners": owners,
            },
        },
    ]

    return {
        "schema_version": "incident_action_plan.v1",
        "incident_id": incident_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "environment": environment,
        "service": service,
        "suspected_owners": owners,
        "actions": actions,
    }


def build_teams_body(packet: dict, jira_ref: dict | None) -> str:
    return _build_teams_body(packet, jira_ref)


def build_pr_notes(packet: dict, jira_ref: dict | None) -> str:
    """Build the content for .opsrunbook/pr-notes/{JIRA_KEY}.md"""
    lines = [
        f"# Incident {packet.get('incident_id', 'N/A')}",
        "",
        f"- **Service**: {packet.get('service', 'N/A')}",
        f"- **Environment**: {packet.get('environment', 'N/A')}",
        f"- **Collector Run ID**: {packet.get('collector_run_id', 'N/A')}",
        f"- **Created At**: {packet.get('model_trace', {}).get('created_at', 'N/A')}",
    ]

    tw = packet.get("time_window", {})
    if tw:
        lines.append(f"- **Time Window**: {tw.get('start', '')} to {tw.get('end', '')}")

    if jira_ref:
        key = jira_ref.get("jira_issue_key", "")
        url = jira_ref.get("jira_url", "")
        lines.append(f"- **Jira**: [{key}]({url})")

    erefs = packet.get("all_evidence_refs", [])
    if erefs:
        lines.append("")
        lines.append("## Evidence")
        for e in erefs[:15]:
            lines.append(f"- `s3://{e.get('s3_bucket', '')}/{e.get('s3_key', '')}` "
                         f"({e.get('collector_type', '?')}, {e.get('byte_size', 0)} bytes)")

    findings = packet.get("findings", [])
    if findings:
        lines.append("")
        lines.append("## Findings")
        for f in findings[:10]:
            lines.append(f"- [{f.get('confidence', 0):.0%}] {f.get('summary', '')[:200]}")

    lines.append("")
    return "\n".join(lines)


def build_pr_body(packet: dict, jira_ref: dict | None) -> str:
    """Build the PR description body."""
    lines = [
        f"## Incident `{packet.get('incident_id', 'N/A')}`",
        "",
        f"**Service**: {packet.get('service', 'N/A')} | "
        f"**Environment**: {packet.get('environment', 'N/A')}",
        "",
    ]

    if jira_ref:
        key = jira_ref.get("jira_issue_key", "")
        url = jira_ref.get("jira_url", "")
        lines.append(f"Jira: [{key}]({url})")
        lines.append("")

    findings = packet.get("findings", [])
    if findings:
        lines.append(f"### {len(findings)} Finding(s)")
        for f in findings[:5]:
            lines.append(f"- [{f.get('confidence', 0):.0%}] {f.get('summary', '')[:150]}")
        lines.append("")

    erefs = packet.get("all_evidence_refs", [])
    lines.append(f"Evidence objects: {len(erefs)}")
    lines.append("")
    lines.append("---")
    lines.append("*Auto-generated by opsrunbook-copilot*")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# LLM-powered content generation
# ---------------------------------------------------------------------------

def _packet_summary(packet: dict) -> str:
    """Compact text representation of a packet for LLM prompts."""
    parts = [
        f"Incident: {packet.get('incident_id', 'N/A')}",
        f"Service: {packet.get('service', 'N/A')}",
        f"Environment: {packet.get('environment', 'N/A')}",
        f"Time Window: {json.dumps(packet.get('time_window', {}))}",
    ]
    for f in packet.get("findings", [])[:10]:
        parts.append(f"Finding [{f.get('confidence', 0):.0%}]: {f.get('summary', '')[:300]}")
    for h in packet.get("hypotheses", [])[:5]:
        parts.append(f"Hypothesis [{h.get('confidence', 0):.0%}]: {h.get('summary', '')[:300]}")
    for a in packet.get("next_actions", [])[:5]:
        parts.append(f"Action: {a.get('summary', '')[:200]}")
        for cmd in a.get("commands", [])[:2]:
            parts.append(f"  Command: {cmd[:200]}")
    for lim in packet.get("limits", [])[:5]:
        parts.append(f"Limit: {lim[:200]}")
    for o in packet.get("suspected_owners", [])[:3]:
        parts.append(f"Suspected owner: {o.get('repo', '?')} (confidence={o.get('confidence', 0):.0%})")
    erefs = packet.get("all_evidence_refs", [])
    parts.append(f"Evidence objects: {len(erefs)}")
    return "\n".join(parts)


def generate_action_content_llm(packet: dict) -> dict | None:
    """Single LLM call that returns both Jira description and PR body.

    Returns {"jira_description": str, "pr_body": str} or None on failure.
    """
    try:
        from llm_client import get_llm
        llm = get_llm(provider=LLM_PROVIDER, model=LLM_MODEL or None)
        if llm is None:
            return None

        from pydantic import BaseModel, Field
        from langchain_core.messages import SystemMessage, HumanMessage

        class ActionContent(BaseModel):
            jira_description: str = Field(
                description="Jira ticket description in Jira wiki markup (h3., -, {code}, etc). Max 3000 chars."
            )
            pr_body: str = Field(
                description="GitHub PR description in GitHub-flavored Markdown. Must start with <!-- opsrunbook_copilot: true -->. Max 4000 chars."
            )

        structured_llm = llm.with_structured_output(ActionContent)
        summary = _packet_summary(packet)

        system_prompt = (
            "You are an SRE handling an incident. Generate TWO pieces of content from the same analysis:\n"
            "1. jira_description: A Jira ticket description using Jira wiki markup (h3., -, {code}, etc). "
            "Include summary, findings, hypotheses, recommended next steps. Under 3000 chars.\n"
            "2. pr_body: A GitHub PR description using GitHub-flavored Markdown. "
            "Include incident summary, root cause analysis, proposed investigation approach, "
            "evidence summary, and 'Human review required' note. "
            "MUST start with <!-- opsrunbook_copilot: true --> on the first line. Under 4000 chars."
        )
        user_prompt = f"Generate action content for this incident:\n\n{summary}"

        print(json.dumps({
            "msg": "llm_request",
            "step": "actions_runner",
            "provider": LLM_PROVIDER,
            "system_prompt": system_prompt[:500],
            "user_prompt": user_prompt[:2000],
            "user_prompt_length": len(user_prompt),
        }))

        result: ActionContent = structured_llm.invoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt),
        ])

        print(json.dumps({
            "msg": "llm_response",
            "step": "actions_runner",
            "jira_description_length": len(result.jira_description),
            "pr_body_length": len(result.pr_body),
            "jira_description_preview": result.jira_description[:1000],
            "pr_body_preview": result.pr_body[:1000],
        }))

        return {"jira_description": result.jira_description, "pr_body": result.pr_body}
    except Exception as e:
        print(json.dumps({"msg": "llm_content_gen_failed", "error": str(e)[:500]}))
        return None
